# Data Processing Job
resources:
  jobs:
    data_processing_job:
      name: data_processing_job

      trigger:
        # Run this job every day, exactly one day from the last run; see https://docs.databricks.com/api/workspace/jobs/create#trigger
        periodic:
          interval: 1
          unit: DAYS

      #email_notifications:
      #  on_failure:
      #    - your_email@example.com

      tasks:

        - task_key: data_processing_task
          environment_key: default
          python_wheel_task:
            package_name: dab_app
            entry_point: job1
            named_parameters:
              env: ${bundle.target}
              batch_size: "1000"
              input_path: "/data/input"

      # A list of task execution environment specifications that can be referenced by tasks of this job.
      environments:
        - environment_key: default

          # Full documentation of this spec can be found at:
          # https://docs.databricks.com/api/workspace/jobs/create#environments-spec
          spec:
            client: "2"
            dependencies:
              - ../dist/*.whl
